


# adb shell pm uninstall --user 0 com.google.android.gms
# adb shell pm uninstall --user 0 com.google.android.gms
# adb shell pm uninstall --user 0 com.google.android.gsf
# adb shell pm uninstall --user 0 com.google.android.gsf
# adb shell pm uninstall --user 0 com.google.android.packageinstaller
# adb shell pm uninstall --user 0 com.google.android.packageinstaller
# adb shell pm uninstall --user 0 com.samsung.android.themecenter
# adb shell pm uninstall --user 0 com.samsung.android.themecenter
# adb shell pm uninstall --user 0 com.samsung.android.themestore
# adb shell pm uninstall --user 0 com.samsung.android.themestore
# adb shell pm uninstall --user 0 com.samsung.upsmtheme
adb shell pm uninstall --user 0 com.android.chrome         
adb shell pm uninstall --user 0 com.android.stk 
adb shell pm uninstall --user 0 com.android.stk2
adb shell pm uninstall --user 0 com.android.vending
adb shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb shell pm uninstall --user 0 com.dsi.ant.server
adb shell pm uninstall --user 0 com.dsi.ant.service.socket
adb shell pm uninstall --user 0 com.ebay.mobile            
adb shell pm uninstall --user 0 com.enhance.gameservice                                                      
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.gd.mobicore.pa     
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.backuptransport
adb shell pm uninstall --user 0 com.google.android.configupdater
adb shell pm uninstall --user 0 com.google.android.ext.services
adb shell pm uninstall --user 0 com.google.android.ext.shared
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.gm
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.gsf.login
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.google.android.setupwizard
adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.google.android.tts
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.webview
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.microsoft.office.excel
adb shell pm uninstall --user 0 com.microsoft.office.onenote
adb shell pm uninstall --user 0 com.microsoft.office.powerpoint
adb shell pm uninstall --user 0 com.microsoft.office.word
adb shell pm uninstall --user 0 com.microsoft.skydrive
# adb shell pm uninstall --user 0 com.osp.app.signin
adb shell pm uninstall --user 0 com.samsung.SMT
adb shell pm uninstall --user 0 com.samsung.aasaservice
adb shell pm uninstall --user 0 com.samsung.advp.imssettings
adb shell pm uninstall --user 0 com.samsung.android.MtpApplication
adb shell pm uninstall --user 0 com.samsung.android.SettingsReceiver
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb shell pm uninstall --user 0 com.samsung.android.app.accesscontrol
adb shell pm uninstall --user 0 com.samsung.android.app.appupdater
adb shell pm uninstall --user 0 com.samsung.android.app.assistantmenu
adb shell pm uninstall --user 0 com.samsung.android.app.colorblind
adb shell pm uninstall --user 0 com.samsung.android.app.filterinstaller
adb shell pm uninstall --user 0 com.samsung.android.app.galaxyfinder
adb shell pm uninstall --user 0 com.samsung.android.app.memo
adb shell pm uninstall --user 0 com.samsung.android.app.mirrorlink
adb shell pm uninstall --user 0 com.samsung.android.app.scrollcapture
adb shell pm uninstall --user 0 com.samsung.android.app.simplesharing
adb shell pm uninstall --user 0 com.samsung.android.app.soundpicker
adb shell pm uninstall --user 0 com.samsung.android.app.talkback
adb shell pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
adb shell pm uninstall --user 0 com.samsung.android.bbc.bbcagent
adb shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb shell pm uninstall --user 0 com.samsung.android.calendar
adb shell pm uninstall --user 0 com.samsung.android.clipboarduiservice
adb shell pm uninstall --user 0 com.samsung.android.communicationservice
adb shell pm uninstall --user 0 com.samsung.android.contacts
adb shell pm uninstall --user 0 com.samsung.android.coreapps
adb shell pm uninstall --user 0 com.samsung.android.dlp.service
adb shell pm uninstall --user 0 com.samsung.android.drivelink.stub
adb shell pm uninstall --user 0 com.samsung.android.easysetup
adb shell pm uninstall --user 0 com.samsung.android.email.provider
adb shell pm uninstall --user 0 com.samsung.android.email.provider
adb shell pm uninstall --user 0 com.samsung.android.fmm
adb shell pm uninstall --user 0 com.samsung.android.framework.res
adb shell pm uninstall --user 0 com.samsung.android.game.gamehome
adb shell pm uninstall --user 0 com.samsung.android.game.gametools
adb shell pm uninstall --user 0 com.samsung.android.incallui
adb shell pm uninstall --user 0 com.samsung.android.intelligenceservice2
adb shell pm uninstall --user 0 com.samsung.android.keyguardwallpaperupdator
adb shell pm uninstall --user 0 com.samsung.android.location
adb shell pm uninstall --user 0 com.samsung.android.lool
adb shell pm uninstall --user 0 com.samsung.android.mdm
adb shell pm uninstall --user 0 com.samsung.android.messaging
adb shell pm uninstall --user 0 com.samsung.android.networkdiagnostic
adb shell pm uninstall --user 0 com.samsung.android.oneconnect
adb shell pm uninstall --user 0 com.samsung.android.provider.filterprovider
adb shell pm uninstall --user 0 com.samsung.android.provider.shootingmodeprovider
adb shell pm uninstall --user 0 com.samsung.android.providers.context
adb shell pm uninstall --user 0 com.samsung.android.scloud
adb shell pm uninstall --user 0 com.samsung.android.sdk.handwriting
adb shell pm uninstall --user 0 com.samsung.android.sdk.professionalaudio.app.audioconnectionservice
adb shell pm uninstall --user 0 com.samsung.android.sdk.professionalaudio.utility.jammonitor
adb shell pm uninstall --user 0 com.samsung.android.securitylogagent
adb shell pm uninstall --user 0 com.samsung.android.sm
adb shell pm uninstall --user 0 com.samsung.android.sm.devicesecurity
adb shell pm uninstall --user 0 com.samsung.android.sm.policy
adb shell pm uninstall --user 0 com.samsung.android.sm.provider
adb shell pm uninstall --user 0 com.samsung.android.smartface
adb shell pm uninstall --user 0 com.samsung.android.svcagent
adb shell pm uninstall --user 0 com.samsung.android.tzdata.update
adb shell pm uninstall --user 0 com.samsung.android.uds
adb shell pm uninstall --user 0 com.samsung.android.universalswitch
adb shell pm uninstall --user 0 com.samsung.android.video
adb shell pm uninstall --user 0 com.samsung.android.videolist
adb shell pm uninstall --user 0 com.samsung.android.voicewakeup
adb shell pm uninstall --user 0 com.samsung.android.weather
adb shell pm uninstall --user 0 com.samsung.app.newtrim
adb shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb shell pm uninstall --user 0 com.samsung.cmh
adb shell pm uninstall --user 0 com.samsung.crane
adb shell pm uninstall --user 0 com.samsung.dcmservice
adb shell pm uninstall --user 0 com.samsung.hs20provider
adb shell pm uninstall --user 0 com.samsung.klmsagent
adb shell pm uninstall --user 0 com.samsung.knox.appsupdateagent
adb shell pm uninstall --user 0 com.samsung.knox.rcp.components
adb shell pm uninstall --user 0 com.samsung.knox.securefolder
adb shell pm uninstall --user 0 com.samsung.rcs
adb shell pm uninstall --user 0 com.samsung.safetyinformation
adb shell pm uninstall --user 0 com.samsung.sec.android.application.csc
adb shell pm uninstall --user 0 com.samsung.storyservice
adb shell pm uninstall --user 0 com.samsung.svoice.sync
adb shell pm uninstall --user 0 com.samsung.ucs.agent.boot
adb shell pm uninstall --user 0 com.samsung.voiceserviceplatform
adb shell pm uninstall --user 0 com.sec.android.app.DataCreate
adb shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb shell pm uninstall --user 0 com.sec.android.app.applinker
adb shell pm uninstall --user 0 com.sec.android.app.billing
adb shell pm uninstall --user 0 com.sec.android.app.bluetoothtest
adb shell pm uninstall --user 0 com.sec.android.app.camera
adb shell pm uninstall --user 0 com.sec.android.app.chromecustomizations
adb shell pm uninstall --user 0 com.sec.android.app.clockpackage
adb shell pm uninstall --user 0 com.sec.android.app.dictionary  
adb shell pm uninstall --user 0 com.sec.android.app.easylauncher
adb shell pm uninstall --user 0 com.sec.android.app.factorykeystring
adb shell pm uninstall --user 0 com.sec.android.app.fm
adb shell pm uninstall --user 0 com.sec.android.app.hwmoduletest
adb shell pm uninstall --user 0 com.sec.android.app.launcher
adb shell pm uninstall --user 0 com.sec.android.app.magnifier
adb shell pm uninstall --user 0 com.sec.android.app.music
adb shell pm uninstall --user 0 com.sec.android.app.myfiles
adb shell pm uninstall --user 0 com.sec.android.app.parser
adb shell pm uninstall --user 0 com.sec.android.app.personalization
adb shell pm uninstall --user 0 com.sec.android.app.popupcalculator
adb shell pm uninstall --user 0 com.sec.android.app.ringtoneBR
adb shell pm uninstall --user 0 com.sec.android.app.safetyassurance
adb shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall --user 0 com.sec.android.app.servicemodeapp
adb shell pm uninstall --user 0 com.sec.android.app.shealth
adb shell pm uninstall --user 0 com.sec.android.app.simsettingmgr
adb shell pm uninstall --user 0 com.sec.android.app.soundalive
adb shell pm uninstall --user 0 com.sec.android.app.sysscope
adb shell pm uninstall --user 0 com.sec.android.app.voicenote
adb shell pm uninstall --user 0 com.sec.android.app.wlantest
adb shell pm uninstall --user 0 com.sec.android.daemonapp  
adb shell pm uninstall --user 0 com.sec.android.easyMover.Agent
adb shell pm uninstall --user 0 com.sec.android.inputmethod
adb shell pm uninstall --user 0 com.sec.android.omc
adb shell pm uninstall --user 0 com.sec.android.service.health
adb shell pm uninstall --user 0 com.sec.android.widgetapp.samsungapps
adb shell pm uninstall --user 0 com.sec.app.samsungprintservice
adb shell pm uninstall --user 0 com.sec.enterprise.knox.attestation
adb shell pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
adb shell pm uninstall --user 0 com.sec.knox.foldercontainer
adb shell pm uninstall --user 0 com.sec.knox.knoxsetupwizardclient
adb shell pm uninstall --user 0 com.sec.knox.switcher
adb shell pm uninstall --user 0 com.sec.knox.switcher  
adb shell pm uninstall --user 0 com.sec.phone
adb shell pm uninstall --user 0 com.skype.raider                           
adb shell pm uninstall --user 0 de.axelspringer.yana.zeropage
adb shell pm uninstall --user 0 flipboard.boxer.app
adb shell pm uninstall --user 0 org.simalliance.openmobileapi.service 
